### ISSUE TITLE
Deprecate Shadow-Piercing descendant combinator

### ISSUE THREAD

**Issue by valakis** [skawa-universe/skawa_components#4]
Deprecate the `/deep/` is selector because:
- It's deprecated, and removed from the Firefox, IE, and Edge,
- The [sass](https://github.com/sass/dart-sass) package, can't parse the `/deep` selector since version 1.0.0-beta.1.

**Comment by daniel-v** [comment]
Assigned `bug` to this as reliance on `/deep/` selector break the visuals of the UI.

**Comment by daniel-v** [comment]
blocked by: dart-lang/angular2#454

**Comment by valakis** [comment]
resvoled in #42
