### ISSUE TITLE
Data Table doesn't update when data changes

### ISSUE THREAD

**Issue by DigNZ** [skawa-universe/skawa_components#44]
Perhaps I'm doing something wrong (I can't find documentation).
I'm using skawa-data-table with [data]="rowData"

When I add elements to rowData (which is a List<RowData>) the table doesn't update, however if I toggle the select all check box then the new row appears.

I've tried ChangeDetectorRef.detectChanges and also tried calling methods on the component such as markAllRowsChecked to try and trigger that effect to update the list. Neither work and would be hacks if they are.

I think its missing a trigger when elements are added to the data.

**Comment by szepeshazi** [comment]
@DigNZ Our Skawa Material components use `OnPush` change detection [strategy](https://webdev.dartlang.org/angular/note/effective/change-detection). This means that for the table to update, you need to pass a new rowData `List` instance. 

If this was your code before:
```
List<T> rowData;
...
rowData.add(item);
```

you should replace it with:
```
List<T> rowData;
...
rowData = List.from(rowData)..add(item);
```
This will trigger change detection on the bound input List.

**Comment by DigNZ** [comment]
That works. Thanks for your help here.
