### ISSUE TITLE
Data table demo isn't working

### ISSUE THREAD

**Issue by anthonyant97** [skawa-universe/skawa_components#47]
Hi there, I try to run the data table but I got some errors in the code. Can you please update your demo? 
The errors are :
Missing concrete implementations of getter RowData.classes and setter RowData.classes.  in `class SampleRowData implements RowData { ...`

and

The argument type '(String, String) → String' can't be assigned to the parameter type '(dynamic, dynamic) → dynamic'. in `return mapped.isNotEmpty ? mapped.reduce(_aggregateReducer) : '-';`

**Comment by valakis** [comment]
Hello i'm trying to ship an updated demo in the next week

**Comment by anthonyant97** [comment]
That's great. Hope you can update it well

**Comment by szepeshazi** [comment]
@anthonyant97 Thanks for reporting this!

Could you help us with further details so we can reproduce the issue you are experiencing?
* What is your dart version? `dart --version`
* In which package did you encounter the above errors? Was it in `skawa_components` or `skawa_components_example`?
* How did you encounter the errors? During build, when running tests or in the browser console (when serving `skawa_components_example`)? What was the exact command you used before hitting the errors?

Many thanks!
András

**Comment by anthonyant97** [comment]
@szepeshazi Sure

- My dart version is 2.1.1
- It was in `skawa_components_example`
- Branch master
- After I copied the data_table_demo.dart and data_table_demo.html, it shows red line error on line 44 and 104 (my first post). I already added `skawa_material_components: ^1.0.0+2` in dependencies

**Comment by szepeshazi** [comment]
@anthonyant97 Thanks! That explains it. 

I'm afraid the master branch of `skawa_components_example` is a bit behind and it has not been upgraded to Dart2 / Angular5 yet. @valakis is working on it and will merge into the master soon. 

Meanwhile you can try checking out the `dart2-update` branch, then running `pub get` and build again.

**Comment by anthonyant97** [comment]
@szepeshazi I checked `dart2-update` branch and the data_table_demo is working! 

I see that there's `colRenderer` property for customize column, do you have any example for it?

**Comment by szepeshazi** [comment]
We've updated the `master` branch of `skawa_components_example` and now it is running on Dart 2 and Angular 5. Furthermore, one of the data table examples has been supplemented with a custom column renderer. 

Check out the last of the [data table examples](https://skawa-universe.github.io/skawa_components_example/#data-table-demo), where the last column's percentage value is now rendered by a material progress bar. The [example source](https://github.com/skawa-universe/skawa_components_example/tree/master/lib/data_table_demo/wr_table) will hopefully help you to implement data tables with custom rendered columns.

**Comment by anthonyant97** [comment]
Wow that's great! It's very helpful and easier to understand!

Thankyou @valakis @szepeshazi I will close this issue now.
