### ISSUE TITLE
Add support for angular_components 0.12.0

### ISSUE THREAD

**Issue by jans-y** [skawa-universe/skawa_components#48]
Hi,

I would like to ask you if you could add support for the newest version of the angular_components library - 0.12.0.

Thank you.

**Comment by alescdb** [comment]
Hi,

In the meantime you can use in your `pubspec.yaml`

```
dependency_overrides:
  angular_components: ^0.12.0
```

**Comment by valakis** [comment]
I will trying to release a new version in this week

**Comment by valakis** [comment]
I'm relased a new version. The 5.3.0 support will be shipped with dart 2.3.0 stable version
