### ISSUE TITLE
Material Data Table change columns at runtime

### ISSUE THREAD

**Issue by ScottMichaud** [skawa-universe/skawa_components#50]
I realize this is probably outside the scope of Data Table, but I have not been able to define columns at runtime. In my situation, the columns are provided on initialization from a config file. It can vary based on how the app is loaded.

Is this supported? How would I go about doing this?

**Comment by valakis** [comment]
Sorry for the late anwser it is not supported yet, i will expose a `ChangeDetectorRef ` from the `SkawaDataTableComponent` with that the colums can be painted, i will ship a new version for this in the next week.

**Comment by ScottMichaud** [comment]
Thanks!

**Comment by valakis** [comment]
I released a new version with an exposed `ChangeDetectorRef`. For the usage see at the `WrTableComponent` in the example repo (that one is not lightes example).
