### ISSUE TITLE
Table stripes are messed up after table sort

### ISSUE THREAD

**Issue by Soundbytes** [skawa-universe/skawa_components#51]
I have run into a problem with the sortable table.
A newly created table is striped alternating in gray and white. However after a table sort the stripes get messed up.

![table_stripes_issue](https://user-images.githubusercontent.com/2970124/57174939-3d7ed880-6e46-11e9-8609-34b8d8d70e5e.PNG)

**Comment by daniel-v** [comment]
@valakis , I can give this a go, although @Soundbytes, I'd be happy if you could provide me with a simple repro for this or a test case in the form of a pull request/gist. It would definitely speed things up. Willing to collaborate on this?

**Comment by Soundbytes** [comment]
Great, I see that you are already working on a fix. Do you still need input from my side?
