### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by hamedsbt** [skawa-universe/skawa_components#56]
Hello, I got this error and can't build:
The `build_runner` version â€“ 1.3.3 â€“ is not within the allowed constraint â€“ >=1.5.0 <2.0.0.

**Comment by valakis** [comment]
Hello, i will check it in the next week

**Comment by hamedsbt** [comment]
I understand my mistake, because I'm using WebStorm and the sample content: "AngularDart Web App- ..." with SDK 2.4 and recent version "skawa_material_components: ^1.2.0" So I got above error.
The solution is: Use recent version of dependecy too.
My working pubspec.yaml contains:
#------------------------------------------------
name: angular_components_test
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Hamedsbt <Hamedsbt@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^0.14.0-alpha
  skawa_material_components: ^1.2.0

dev_dependencies:
  angular_test: ^2.3.1
  build_runner: ^1.6.1
  build_test: ^0.10.8
  build_web_compilers: ^2.1.2
  pedantic: ^1.8.0
  test: ^1.6.4
#------------------------------------------------

Note: some dependencies are optional.

Thank you developers ;)
