### ISSUE TITLE
github release/tag version is not catch up with pub version

### ISSUE THREAD

**Issue by oonid** [skawa-universe/skawa_components#57]
hi, thank you for the actively-develop-complimentary-components for AngularDart!

I didn't get notification from GitHub for its latest release version,
and it turns out the release/tag version on GitHub is not update.

would be great if you update the [release/tag versions](https://github.com/skawa-universe/skawa_components/releases).

and one more thing, the image on project README is broken.

**Comment by valakis** [comment]
Hello it's my mistake, i will trying to find time in this week to fix that.

**Comment by valakis** [comment]
Hello, i added the tags for the previous relases, and changed the broken image in the ongoing release
